#!/bin/sh
# git-version.sh -- generate version-git.h for the tizee tmux fork.
#
# Usage: git-version.sh <srcdir> <outfile>
#
# Emits two macros consumed by tmux.c:
#   TMUX_GIT_HASH   short commit hash, or "" outside a git checkout
#   TMUX_GIT_EPOCH  commit unix time (long), or 0 if unknown
#
# The file is rewritten only when its content changes, so an unchanged commit
# does not force tmux.c to recompile on every build.

set -eu

srcdir=${1:-.}
out=${2:-version-git.h}

hash=""
epoch="0"

# Only trust git when it exists and srcdir is a real work tree.
if command -v git >/dev/null 2>&1 &&
   git -C "$srcdir" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
	hash=$(git -C "$srcdir" rev-parse --short HEAD 2>/dev/null || echo "")
	epoch=$(git -C "$srcdir" log -1 --format=%ct 2>/dev/null || echo "0")
	[ -n "$epoch" ] || epoch="0"
fi

tmp="$out.tmp$$"
{
	echo "/* Generated by git-version.sh -- do not edit. */"
	echo "#ifndef VERSION_GIT_H"
	echo "#define VERSION_GIT_H"
	echo "#define TMUX_GIT_HASH \"$hash\""
	echo "#define TMUX_GIT_EPOCH ${epoch}L"
	echo "#endif /* VERSION_GIT_H */"
} >"$tmp"

if [ -f "$out" ] && cmp -s "$tmp" "$out"; then
	rm -f "$tmp"
else
	mv -f "$tmp" "$out"
fi
